{{- if .Values.registry.enabled -}}
{{- $basicAuth := printf "%s:%s" .Values.registry.account.username .Values.registry.account.hash -}}
# used by the registry ingress to authenticate users
apiVersion: v1
kind: Secret
metadata:
  name: registry-basic-auth
type: Opaque
data:
  auth: {{ $basicAuth | b64enc }}
---
{{- if .Values.registry.create -}}
{{- $kuberoUiHost := (index .Values.ingress.hosts 0) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubero-registry-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.registry.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.registry.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: registry
  name: kubero-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      run: registry
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
      - name: registry
        image: registry:3
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_AUTH
          value: token
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: http{{ if .Values.ingress.tls }}s{{ end }}://{{ $kuberoUiHost.host }}{{ $kuberoUiHost.path }}/api/registry/token
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: {{ .Values.registry.host }}
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: todo.kubero.dev # TODO
        - name: REGISTRY_AUTH_TOKEN_JWKS
          value: /auth/jwk
        - name: OTEL_TRACES_EXPORTER
          value: "none"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
          subPath: registry
        - name: jwt-pubkey
          mountPath: /auth
          readOnly: true
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: kubero-registry-data-pvc
      - name: jwt-pubkey
        secret:
          defaultMode: 0o640
          # created by UI on startup
          secretName: registry-jwt-pubkey
---
apiVersion: v1
kind: Service
metadata:
  name: kubero-registry
spec:
  type: ClusterIP
  selector:
    run: registry
  ports:
    - name: registry-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubero-registry-ingress
  labels:
    {{- include "kubero.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.registry.host }}
      secretName: kubero-registry-tls
  rules:
    - host: {{ .Values.registry.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubero-registry
                port:
                  number: 5000
{{- end }}
{{- end }}